---

- name: install everything
  hosts: 127.0.0.1
  connection: local
  become: yes

  vars:
    distribution: bionic

  tasks:

  - name: set apt-fast config
    command: "{{ item }}"
    with_items:
      - "echo debconf apt-fast/maxdownloads string 8 | sudo debconf-set-selections"
      - "echo debconf apt-fast/dlflag boolean true | sudo debconf-set-selections"
      - "echo debconf apt-fast/aptmanager string apt-get | sudo debconf-set-selections"

  - name: add apt signing keys
    apt_key:
      url: "{{ item }}"
      state: present
    with_items:
      - "https://couchdb.apache.org/repo/bintray-pubkey.asc"

  - name: add apt-keys from keyservers
    apt_key:
      keyserver: "{{ item.keyserver }}"
      id: "{{ item.id }}"
    with_items:
      - { keyserver: "hkp://keyserver.ubuntu.com:80", id: "931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90" }

  - name: add repositories
    apt_repository:
      repo: "{{ item }}"
      state: present
    with_items:
      - "ppa:apt-fast/stable"
      - "ppa:kelleyk/emacs"
      - "deb https://apache.bintray.com/couchdb-deb {{ distribution }} main"
      - "http://repository.spotify.com stable non-free"

  - name: add specific repository into files
    apt_repository:
      repo: "{{ item.src }}"
      state: present
      filename: "{{ item.file }}"
    with_items:
      - { src: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main', file: vscode.list }

  - name: install apt-fast
    apt:
      update_cache: yes
      name: apt-fast
      state: present

  - name: download and install deb files
    apt:
      deb: "{{ item }}"
      state: present
    with_items:
      - "https://github.com/BurntSushi/ripgrep/releases/download/11.0.1/ripgrep_11.0.1_amd64.deb"
      - "https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb"
      - "https://discordapp.com/api/download?platform=linux&format=deb"

  - name: install packages
    apt:
      update_cache: yes
      upgrade: dist
      state: present
      name:
        - emacs26
        - gnutls
        - gnutls-bin
        - pkg-config
        - build-essential
        - texinfo
        - libx11-dev
        - libxpm-dev
        - libjpeg-dev
        - libpng-dev
        - libgif-dev
        - libtiff-dev
        - libgtk2.0-dev
        - libncurses-dev
        - gnutls-dev
        - libgtk-3-dev
        - dbus-x11
        - python-pip
        - python-pip3
        - sshpass
        - silversearcher-ag
        - xsel
        - figlet
        - xset
        - firefox
        - autopep8
        - git-grep
        - tree
        - ipython3
        - python-pep8
        - autojump
        - code
        - curl
        - wget
        - python3-dev
        - keychain
        - golang-go
        - nodejs
        - npm
        - avfs
        - firewalld
        - openssh-server
        - apt-transport-https
        - dotnet-sdk-2.2
        - spotify-client
        - steam


  - name: install python packages
    pip:
      executable: pip3
      name:
      - astropy
      - black
      - epc
      - flake8
      - importmagic
      - ipython
      - isort
      - jedi
      - Jinja2
      - numpy
      - rebound-cli
      - scipy
      - paramiko
      - pep8
      - pymongo
      - pysnooper
      - Sphinx
      - yapf

  - name: install strans from dotnet
    command: dotnet tool install -g strans
    args:
      creates: "~/.dotnet/tools/strans"

  - name: link strans to local bin directory
    command: ln -s ~/.dotnet/tools/strans ~/bin/strans
    args:
      creates: "~/bin/strans"

  - name: create emacs service
    systemd:
      name: emacs
      enable: yes
      state: started
